"""SQLAlchemy ORM models for GoComet Nova trade document pipeline and observability."""

import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    JSON,
)
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


def generate_uuid() -> str:
    """Generate a string UUID."""
    return str(uuid.uuid4())


class Document(Base):
    """Uploaded trade document metadata and lifecycle state."""
    __tablename__ = "documents"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    filename = Column(String(255), nullable=False)
    file_path = Column(String(500), nullable=False)
    file_hash = Column(String(64), nullable=False, index=True)
    mime_type = Column(String(100), nullable=False)
    file_size_bytes = Column(Integer, nullable=False)
    doc_type = Column(String(50), nullable=False, default="commercial_invoice")
    status = Column(String(50), nullable=False, default="PENDING")
    uploaded_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    extractions = relationship("Extraction", back_populates="document", cascade="all, delete-orphan")
    validations = relationship("Validation", back_populates="document", cascade="all, delete-orphan")
    decisions = relationship("Decision", back_populates="document", cascade="all, delete-orphan")
    runs = relationship("Run", back_populates="document")


class Extraction(Base):
    """Normalized structured data extracted by the Extractor Agent."""
    __tablename__ = "extractions"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    document_id = Column(String(36), ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    raw_json = Column(JSON, nullable=False)
    consignee = Column(String(255), nullable=True)
    hs_code = Column(String(50), nullable=True)
    pol = Column(String(100), nullable=True)
    pod = Column(String(100), nullable=True)
    incoterm = Column(String(20), nullable=True)
    description = Column(Text, nullable=True)
    gross_weight = Column(String(50), nullable=True)
    invoice_number = Column(String(100), nullable=True)
    extraction_method = Column(String(50), nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    document = relationship("Document", back_populates="extractions")


class Validation(Base):
    """Validation outcomes generated by the Validator Agent."""
    __tablename__ = "validations"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    document_id = Column(String(36), ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    overall_status = Column(String(50), nullable=False)
    results_json = Column(JSON, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    document = relationship("Document", back_populates="validations")


class Decision(Base):
    """Deterministic routing action and drafted response generated by the Router Agent."""
    __tablename__ = "decisions"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    document_id = Column(String(36), ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    decision = Column(String(50), nullable=False)
    reasoning = Column(Text, nullable=False)
    email_draft = Column(Text, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    document = relationship("Document", back_populates="decisions")


class Run(Base):
    """Telemetry, latency, token consumption, and cost tracking for agent execution runs."""
    __tablename__ = "runs"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    document_id = Column(String(36), ForeignKey("documents.id", ondelete="SET NULL"), nullable=True)
    node_name = Column(String(100), nullable=False)
    model_name = Column(String(100), nullable=True)
    latency_ms = Column(Float, nullable=False)
    prompt_tokens = Column(Integer, default=0, nullable=False)
    completion_tokens = Column(Integer, default=0, nullable=False)
    thinking_tokens = Column(Integer, default=0, nullable=False)
    cost_usd = Column(Float, default=0.0, nullable=False)
    status = Column(String(50), nullable=False)
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    document = relationship("Document", back_populates="runs")
